require Pod::Executable.execute_command('node', ['-p',
  'require.resolve(
    "react-native/scripts/react_native_pods.rb",
    {paths: [process.argv[1]]},
  )', __dir__]).strip

platform :ios, '15.0'
use_modular_headers!

require_relative '../node_modules/react-native/scripts/react_native_pods'
require_relative '../node_modules/@react-native-community/cli-platform-ios/native_modules'

target 'BODHI' do
  config = use_native_modules!

  pod 'AppAuth', '2.0.0'
  pod 'GTMAppAuth', '5.0.0'
  pod 'GTMSessionFetcher', :modular_headers => true

  use_react_native!(
    :path => config[:reactNativePath]
  )

  target 'BODHITests' do
    inherit! :complete
  end

  post_install do |installer|
    react_native_post_install(installer)

    installer.pods_project.targets.each do |target|
      target.build_configurations.each do |config|
        config.build_settings['IPHONEOS_DEPLOYMENT_TARGET'] = '15.0'
      end
    end
  end
end